# Generated by Django 5.2.9 on 2025-12-23 15:47

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome completo do candidato', max_length=200, verbose_name='Nome Completo')),
                ('email', models.EmailField(help_text='E-mail do candidato', max_length=254, unique=True, validators=[django.core.validators.EmailValidator()], verbose_name='E-mail')),
                ('telefone', models.CharField(blank=True, help_text='Telefone de contato', max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Telefone deve estar no formato: '+999999999'. Até 15 dígitos permitidos.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Telefone')),
                ('linkedin', models.URLField(blank=True, help_text='URL do perfil no LinkedIn', null=True, verbose_name='LinkedIn')),
                ('curriculo', models.FileField(blank=True, help_text='Arquivo do currículo (PDF, DOC, DOCX)', null=True, upload_to='curriculos/%Y/%m/', verbose_name='Currículo')),
                ('observacoes', models.TextField(blank=True, help_text='Observações gerais sobre o candidato', null=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Candidato',
                'verbose_name_plural': 'Candidatos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='ProcessoSeletivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Título do processo seletivo', max_length=200, verbose_name='Título')),
                ('descricao', models.TextField(help_text='Descrição detalhada do processo seletivo', verbose_name='Descrição')),
                ('vaga', models.CharField(help_text='Nome da vaga', max_length=200, verbose_name='Vaga')),
                ('departamento', models.CharField(blank=True, help_text='Departamento da vaga', max_length=100, null=True, verbose_name='Departamento')),
                ('status', models.CharField(choices=[('aberto', 'Aberto'), ('em_andamento', 'Em Andamento'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], default='aberto', max_length=20, verbose_name='Status')),
                ('data_inicio', models.DateField(help_text='Data de início do processo seletivo', verbose_name='Data de Início')),
                ('data_fim', models.DateField(blank=True, help_text='Data prevista para encerramento', null=True, verbose_name='Data de Fim')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Processo Seletivo',
                'verbose_name_plural': 'Processos Seletivos',
                'ordering': ['-data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Criterio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: Comunicação, Técnica, Criatividade, etc.', max_length=100, verbose_name='Nome do Critério')),
                ('descricao', models.TextField(blank=True, help_text='Descrição detalhada do critério', null=True, verbose_name='Descrição')),
                ('peso', models.DecimalField(decimal_places=2, default=1.0, help_text='Peso do critério no cálculo final (0.01 a 10.00)', max_digits=3, validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(10.0)], verbose_name='Peso')),
                ('ordem', models.PositiveIntegerField(default=0, help_text='Ordem de exibição do critério', verbose_name='Ordem')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('processo_seletivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criterios', to='ranking.processoseletivo', verbose_name='Processo Seletivo')),
            ],
            options={
                'verbose_name': 'Critério de Avaliação',
                'verbose_name_plural': 'Critérios de Avaliação',
                'ordering': ['processo_seletivo', 'ordem', 'nome'],
                'unique_together': {('processo_seletivo', 'nome')},
            },
        ),
        migrations.CreateModel(
            name='RankingCandidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(blank=True, choices=[('S', 'Tier S - Excepcional'), ('A', 'Tier A - Excelente'), ('B', 'Tier B - Bom'), ('C', 'Tier C - Regular'), ('D', 'Tier D - Abaixo da Média'), ('F', 'Tier F - Inadequado')], help_text='Classificação do candidato no processo seletivo', max_length=1, null=True, verbose_name='Tier')),
                ('observacoes_gerais', models.TextField(blank=True, help_text='Observações gerais sobre o desempenho do candidato', null=True, verbose_name='Observações Gerais')),
                ('data_avaliacao', models.DateTimeField(blank=True, help_text='Data em que o candidato foi avaliado', null=True, verbose_name='Data da Avaliação')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rankings', to='ranking.candidato', verbose_name='Candidato')),
                ('processo_seletivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rankings', to='ranking.processoseletivo', verbose_name='Processo Seletivo')),
            ],
            options={
                'verbose_name': 'Ranking de Candidato',
                'verbose_name_plural': 'Rankings de Candidatos',
                'ordering': ['tier', '-data_avaliacao'],
                'unique_together': {('candidato', 'processo_seletivo')},
            },
        ),
        migrations.CreateModel(
            name='AvaliacaoCriterio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.DecimalField(decimal_places=2, help_text='Nota de 0 a 10', max_digits=4, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)], verbose_name='Nota')),
                ('anotacao', models.TextField(blank=True, help_text='Comentários sobre a avaliação neste critério', null=True, verbose_name='Anotação')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('criterio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='ranking.criterio', verbose_name='Critério')),
                ('ranking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_criterios', to='ranking.rankingcandidato', verbose_name='Ranking')),
            ],
            options={
                'verbose_name': 'Avaliação de Critério',
                'verbose_name_plural': 'Avaliações de Critérios',
                'ordering': ['criterio__ordem', 'criterio__nome'],
                'unique_together': {('ranking', 'criterio')},
            },
        ),
    ]
