# Generated by Django 5.2.9 on 2025-12-23 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rankingcandidato',
            options={'ordering': ['tier', 'ordem', '-data_avaliacao'], 'verbose_name': 'Ranking de Candidato', 'verbose_name_plural': 'Rankings de Candidatos'},
        ),
        migrations.AddField(
            model_name='rankingcandidato',
            name='ordem',
            field=models.PositiveIntegerField(default=0, help_text='Ordem do candidato dentro do seu tier', verbose_name='Ordem'),
        ),
    ]
