# Generated by Django 4.2.11 on 2025-12-23 17:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0002_alter_rankingcandidato_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criterio',
            name='peso',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Peso do critério no cálculo final (0.01 a 10.00)', max_digits=4, validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(10.0)], verbose_name='Peso'),
        ),
    ]
